name: Build Unsigned IPA (curl fallback)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Build app for iOS
        run: |
          xcodebuild clean build \
            -project SastraApp.xcodeproj \
            -scheme SastraApp \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build

      - name: Package .app into unsigned IPA
        run: |
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/SastraApp.app Payload/
          zip -r SastraApp.ipa Payload

      - name: Create artifacts folder
        run: |
          mkdir -p output
          mv SastraApp.ipa output/

      - name: Save IPA as artifact via curl (transfer.sh)
        run: |
          echo "Uploading IPA to transfer.sh..."
          curl --upload-file ./output/SastraApp.ipa https://transfer.sh/SastraApp.ipa > ipa_url.txt
          echo "Download URL:"
          cat ipa_url.txt
